version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASSWORD}
      POSTGRES_DB: plumber 
    ports:
      - "5432:5432"
    networks:
      - plumber
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api-service
    ports:
      - "4321:4320"
      - "4330:4330" 
    networks:
      - plumber

  nodeserver:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nodeServer
    networks:
      - plumber
    depends_on:
      - api 
    volumes:
      - ${UNIXSOCKETADDR}:/var/run/docker.sock
      - ${DOCKERBIN}:/usr/bin/docker
      - ${HOSTPATH}/Code-Plumber/runEnv:/app/runEnv
    environment:
      HOSTPATH: ${HOSTPATH}


  goserver1:
    build:
      context: ./goserver
      dockerfile: Dockerfile
    container_name: goserver1
    networks:
      - plumber
    depends_on:
      - api 
    volumes:
      - ${UNIXSOCKETADDR}:/var/run/docker.sock
      - ${DOCKERBIN}:/usr/bin/docker
      - ${HOSTPATH}/Code-Plumber/runEnv:/app/runEnv
    environment:
      HOSTPATH: ${HOSTPATH}

  goserver2:
    build:
      context: ./shareServer
      dockerfile: Dockerfile
    container_name: goserver2
    networks:
      - plumber
    depends_on:
      - api
      - postgres
    environment:
      DATABASE_URL: ${DBURL}

networks:
  plumber:

volumes:
  postgres_data:
